apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-pv
  namespace: dev
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  azureDisk:
    diskName: pg-aksdisk
    diskURI: /subscriptions/c3a93105-712e-4de0-b82d-5433d504d44f/resourceGroups/EPSI/providers/Microsoft.Compute/disks/pg-aksdisk
    cachingMode: ReadWrite
    fsType: ext4
    kind: Managed
