apiVersion: v1
kind: Service
metadata:
  name: php-dev-service
  namespace: dev
spec:
  type: LoadBalancer
  selector:
    app: php-dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
