apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-dev-deployment
  namespace: dev
spec:
  replicas: 2  # Deux réplicas pour une haute disponibilité
  selector:
    matchLabels:
      app: php-dev
  template:
    metadata:
      labels:
        app: php-dev
    spec:
      containers:
        - name: php-dev
          image: epsiregistry.azurecr.io/gestion-produits-server-dev:latest  # Ton image Docker personnalisée
          env:
            - name: PG_HOST
              value: "pg-service"
            - name: PG_PORT
              value: "5432"
            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: user
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: password
            - name: PG_DATABASE
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: database
          ports:
            - containerPort: 8080  # Port exposé par le conteneur PHP
